### ISSUE TITLE
Extract triples process hangs

### ISSUE THREAD

**Issue by vukm** [AKSW/csvimport.ontowiki#13]
After the extraction of triples is started "Please wait" message is shown and then it stays that way and nothing responds.

**Comment by Rahien** [comment]
This happens to me too, but only when I change the Base URI for the extracted triples. The process then hangs at Import started..
Creating component properties and dataset...
If I leave the uri unchanged, everything works fine
![csvimporthangs](https://f.cloud.github.com/assets/1076194/286220/1ed6acc4-9237-11e2-840c-297651b5c3d1.png)
