### ISSUE TITLE
Import only works for existing Knowledge Bases.

### ISSUE THREAD

**Issue by earthquakesan** [AKSW/csvimport.ontowiki#25]
https://github.com/AKSW/csvimport.ontowiki/wiki/HowTo provides misleading informations. New KB can not be created from the CSV file.

**Comment by amrapalijz** [comment]
That's not what it says. You have to create a new knowledge base first and then only upload the csv file.

**Comment by earthquakesan** [comment]
Oh, right. My mistake. =\
Maybe better do it with screenshots?

**Comment by amrapalijz** [comment]
Yes, if you read till the end of that page, there's a link to a short presentation: http://goo.gl/Ayps9.
