### ISSUE TITLE
RDFa

### ISSUE THREAD

**Issue by amrapalijz** [AKSW/csvimport.ontowiki#3]
RDFa was used to suggest a drop-down list for the sdmx attributes. But, now it does not show the drop-down list and it shows an error when an sdmx attirbute is not given as it is mandatory.

**Comment by yamalight** [comment]
works for me o.O

**Comment by amrapalijz** [comment]
Hey,

Ok, thanks for fixing them :-)
Ya, this one apparently worked for one of them too when he typed a  
small letter m instead of capital M !!
Anyways, did you update the extension for them?

Regards,
Amrapali

Quoting Tim Ermilov  
reply@reply.github.com:

> works for me o.O
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/AKSW/csvimport.ontowiki/issues/3#issuecomment-5739670

---

This message was sent using IMP, the Internet Messaging Program.
