### ISSUE TITLE
value for 'type' in the datastructure array

### ISSUE THREAD

**Issue by Sdfendor** [AKSW/csvimport.ontowiki#8]
In der Extension wird ein Array gebildet, der die geparsten Datensätze enthält und dieser wird mittels der Funktion addMultipleStatements eingefügt. Um den Typ zu bestimmen, wird mittels type zwischen 'uri' und 'literal' unterschieden. Bisher werden alle Literale als normale Strings eingelesen, der Einfachheit halber. Ich würde nun gerne Datentypen berücksichtigen. Meine Frage ist, ob es möglich ist, mittels eines weiteren Wertes im Array oder mit anderen Werten für type den Datentyp des Literals zu setzen, sodass ich anstatt eines Strings z.B. einen xsd:integer importieren kann. Bisher ist es mir nur gelungen, später den Datentyp der importierten Datensätze manuell zu ändern, sodass ich beim Exportieren den gewünschten Output erhielt. Ich habe testweise 'literal' in 'integer' verändert, aber das war nur ein Schuss ins Blaue und hat auch nicht funktioniert, es wurde trotzdem ein normaler String importiert.

**Comment by seebi** [comment]
to specify a datatype or language tag, you can use `datatype` and `lang`. This is document in the specification of the php/rdf array: http://docs.api.talis.com/platform-api/output-types/rdf-php
